In [71]:
import numpy as np
import cv2  # Image reading library

In [72]:
def Convolution(image, kernel):
    "Image and kernel should be numpy matrices. Kernel should be 3 x 3"

    _image = np.copy(image)/255
    ry, rx = tuple(image.shape)
    new_image = np.empty_like(_image)
    _image = np.vstack([np.zeros(rx), _image, np.zeros(rx)])
    _image = np.concatenate([np.zeros(ry+2).reshape([-1,1]), _image, np.zeros(ry+2).reshape([-1,1])], axis=1)
    for row in range(1,ry+1):
        for col in range(1,rx+1):
            section = _image[row-1:row+2, col-1:col+2]
            # print(section)
            try: new_image[row-1][col-1] = np.sum(section*kernel)
            except: print(row, col)
    return (new_image)*255


    
def prod(sect, kernel):
    new_element = 0
    for row in range(sect.shape[1]):
        for col in range(sect.shape[0]):
            # print(sect)
            new_element += sect[row][col]*kernel[row][col]
    return new_element


kernel = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
gaussian_blur = np.array([[0.075, 0.124, 0.075], [.124, .204, .124], [.075, .124, .075]])
kernel[0][0]

1

In [73]:
prod = prod(kernel, kernel)
print(prod)
# OR
prod = np.sum(kernel*kernel)
print(prod)
prod = kernel.flatten()@kernel.flatten().T
print(prod)

12
12
12


In [69]:
# kernel2 = initialize_kernel(size=(3,3) , sigma=1.5)
# print((kernel2))
img = cv2.imread('football.png', cv2.IMREAD_GRAYSCALE)
print((img.shape))
img_edges = Convolution(img, kernel)
cv2.imwrite("Edges.png", img_edges)
img_blur = Convolution(img, gaussian_blur)
cv2.imwrite('Gaussian Blur.png', img_blur)
img_gauss_edges = Convolution(img_blur, kernel)
cv2.imwrite('Gaussian Blur + Edges.png', img_gauss_edges)
# cv2.waitKey(0)

(600, 600)


True

In [70]:
ppt_conv = np.array(
    [[50, 165, 67, 0],
    [94, 23, 88, 12],
    [178, 56, 90, 64],
    [234, 208, 78, 123]]
)
# print(ppt_conv.shape)
print(Convolution(ppt_conv, kernel))

[[-353  -28  341  222]
 [-267   83  179  333]
 [-343  338   80  346]
 [-472  400  162  246]]
