In [11]:
import numpy as np
import cv2  # Image reading library

In [12]:
def Convolution(image, kernel):
    "Image and kernel should be numpy matrices. Kernel should be 3 x 3"

    _image = np.copy(image)
    ry, rx = tuple(image.shape)
    new_image = np.empty_like(_image)
    _image = np.vstack([np.zeros(rx), _image, np.zeros(rx)])
    _image = np.concatenate([np.zeros(ry).reshape([-1,1]), _image, np.zeros(ry).reshape([-1,1])], axis=1)
    for row in range(1,ry+1):
        for col in range(1,rx+1):
            section = _image[row-1:row+2, col-1:col+2]
            print(section)
            try: new_image[row-1][col-1] = np.sum(section*kernel)
            except: print(row, col)
    print(new_image.shape)
    return (new_image)


    
def prod(sect, kernel):
    new_element = 0
    for row in range(sect.shape[1]):
        for col in range(sect.shape[0]):
            # print(sect)
            new_element += sect[row][col]*kernel[row][col]
    return new_element


kernel = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]])
kernel[0][0]

1

In [13]:
prod = prod(kernel, kernel)
print(prod)
# OR
prod = np.sum(kernel*kernel)
print(prod)
prod = kernel.flatten()@kernel.flatten().T
print(prod)

12
12
12


In [14]:
# kernel2 = initialize_kernel(size=(3,3) , sigma=1.5)
# print((kernel2))
img = cv2.imread('football.png', cv2.IMREAD_GRAYSCALE)
print((img.shape))
# img = Convolution(img, kernel)
# cv2.imwrite("Edges.png", img)
# cv2.waitKey(0)

(600, 600)


In [15]:
ppt_conv = np.array(
    [[50, 165, 67, 0],
    [94, 23, 88, 12],
    [178, 56, 90, 64],
    [234, 208, 78, 123]]
)
print(ppt_conv.shape)
print(Convolution(ppt_conv, kernel))

(4, 4)
[[  0.   0.   0.]
 [  0.  50. 165.]
 [  0.  94.  23.]]
[[  0.   0.   0.]
 [ 50. 165.  67.]
 [ 94.  23.  88.]]
[[  0.   0.   0.]
 [165.  67.   0.]
 [ 23.  88.  12.]]
[[ 0.  0.  0.]
 [67.  0.  0.]
 [88. 12.  0.]]
[[  0.  50. 165.]
 [  0.  94.  23.]
 [  0. 178.  56.]]
[[ 50. 165.  67.]
 [ 94.  23.  88.]
 [178.  56.  90.]]
[[165.  67.   0.]
 [ 23.  88.  12.]
 [ 56.  90.  64.]]
[[67.  0.  0.]
 [88. 12.  0.]
 [90. 64.  0.]]
[[  0.  94.  23.]
 [  0. 178.  56.]
 [  0. 234. 208.]]
[[ 94.  23.  88.]
 [178.  56.  90.]
 [234. 208.  78.]]
[[ 23.  88.  12.]
 [ 56.  90.  64.]
 [208.  78. 123.]]
[[ 88.  12.   0.]
 [ 90.  64.   0.]
 [ 78. 123.   0.]]
[[  0. 178.  56.]
 [  0. 234. 208.]
 [  0.   0.   0.]]
[[178.  56.  90.]
 [234. 208.  78.]
 [  0.   0.   0.]]
[[ 56.  90.  64.]
 [208.  78. 123.]
 [  0.   0.   0.]]
[[ 90.  64.   0.]
 [ 78. 123.   0.]
 [  0.   0.   0.]]
(4, 4)
[[-353  -28  341  222]
 [-267   83  179  333]
 [-343  338   80  346]
 [-472  400  162  246]]
